<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="30" total="37" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Failed suite [Failed suite [Suite]]]" duration-ms="558136" started-at="2019-12-20T10:45:14Z" finished-at="2019-12-20T10:54:33Z">
    <groups>
    </groups>
    <test name="Test(failed)(failed)(failed)" duration-ms="558136" started-at="2019-12-20T10:45:14Z" finished-at="2019-12-20T10:54:33Z">
      <class name="com.staff.qa.testcases.PlacementPageTest">
        <test-method status="PASS" signature="setExtentReport(org.testng.ITestContext)[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setExtentReport" is-config="true" duration-ms="169" started-at="2019-12-20T10:45:14Z" finished-at="2019-12-20T10:45:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@629075f4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtentReport -->
        <test-method status="PASS" signature="setupBeforeSuite(org.testng.ITestContext)[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setupBeforeSuite" is-config="true" duration-ms="249" started-at="2019-12-20T10:45:15Z" finished-at="2019-12-20T10:45:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@629075f4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeSuite -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setUp" is-config="true" duration-ms="6579" started-at="2019-12-20T10:45:15Z" finished-at="2019-12-20T10:45:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyPlacedConsultantAppearInPlacement_FromRequirement()[pri:9, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="verifyPlacedConsultantAppearInPlacement_FromRequirement" duration-ms="90178" started-at="2019-12-20T10:45:21Z" finished-at="2019-12-20T10:46:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Req-264706-6] but found [Req-264711-6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Req-264706-6] but found [Req-264711-6]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.staff.qa.testcases.PlacementPageTest.verifyPlacedConsultantAppearInPlacement_FromRequirement(PlacementPageTest.java:350)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPlacedConsultantAppearInPlacement_FromRequirement -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="getResult" is-config="true" duration-ms="2129" started-at="2019-12-20T10:46:52Z" finished-at="2019-12-20T10:46:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPlacedConsultantAppearInPlacement_FromRequirement status=FAILURE method=PlacementPageTest.verifyPlacedConsultantAppearInPlacement_FromRequirement()[pri:9, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setUp" is-config="true" duration-ms="6448" started-at="2019-12-20T10:46:54Z" finished-at="2019-12-20T10:47:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyPlacedConsultantAppearInPlacement_FromConsultant()[pri:10, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="verifyPlacedConsultantAppearInPlacement_FromConsultant" duration-ms="82256" started-at="2019-12-20T10:47:00Z" finished-at="2019-12-20T10:48:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPlacedConsultantAppearInPlacement_FromConsultant -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="getResult" is-config="true" duration-ms="1712" started-at="2019-12-20T10:48:22Z" finished-at="2019-12-20T10:48:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPlacedConsultantAppearInPlacement_FromConsultant status=SUCCESS method=PlacementPageTest.verifyPlacedConsultantAppearInPlacement_FromConsultant()[pri:10, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setUp" is-config="true" duration-ms="5806" started-at="2019-12-20T10:48:24Z" finished-at="2019-12-20T10:48:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyEditClientAssignmentFieldsOfPlacementFormFunctionality()[pri:21, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="verifyEditClientAssignmentFieldsOfPlacementFormFunctionality" duration-ms="74142" started-at="2019-12-20T10:48:30Z" finished-at="2019-12-20T10:49:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEditClientAssignmentFieldsOfPlacementFormFunctionality -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="getResult" is-config="true" duration-ms="1706" started-at="2019-12-20T10:49:44Z" finished-at="2019-12-20T10:49:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyEditClientAssignmentFieldsOfPlacementFormFunctionality status=SUCCESS method=PlacementPageTest.verifyEditClientAssignmentFieldsOfPlacementFormFunctionality()[pri:21, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setUp" is-config="true" duration-ms="7102" started-at="2019-12-20T10:49:46Z" finished-at="2019-12-20T10:49:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyCompaniesFilterFunOfPlacementForm1()[pri:29, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="verifyCompaniesFilterFunOfPlacementForm1" duration-ms="29711" started-at="2019-12-20T10:49:53Z" finished-at="2019-12-20T10:50:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Open Placements (6)] but found [Open Placements (7)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Open Placements (6)] but found [Open Placements (7)]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.staff.qa.testcases.PlacementPageTest.verifyCompaniesFilterFunOfPlacementForm1(PlacementPageTest.java:1389)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCompaniesFilterFunOfPlacementForm1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="getResult" is-config="true" duration-ms="2036" started-at="2019-12-20T10:50:23Z" finished-at="2019-12-20T10:50:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyCompaniesFilterFunOfPlacementForm1 status=FAILURE method=PlacementPageTest.verifyCompaniesFilterFunOfPlacementForm1()[pri:29, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setUp" is-config="true" duration-ms="5913" started-at="2019-12-20T10:50:25Z" finished-at="2019-12-20T10:50:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyPlacementDateFilterFunOfPlacementForm()[pri:33, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="verifyPlacementDateFilterFunOfPlacementForm" duration-ms="55176" started-at="2019-12-20T10:50:31Z" finished-at="2019-12-20T10:51:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.PlacementPageTest.verifyPlacementDateFilterFunOfPlacementForm(PlacementPageTest.java:1623)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPlacementDateFilterFunOfPlacementForm -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="getResult" is-config="true" duration-ms="2072" started-at="2019-12-20T10:51:26Z" finished-at="2019-12-20T10:51:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPlacementDateFilterFunOfPlacementForm status=FAILURE method=PlacementPageTest.verifyPlacementDateFilterFunOfPlacementForm()[pri:33, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setUp" is-config="true" duration-ms="5852" started-at="2019-12-20T10:51:28Z" finished-at="2019-12-20T10:51:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifySubmitForApprovalFunctionality1()[pri:35, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="verifySubmitForApprovalFunctionality1" duration-ms="93275" started-at="2019-12-20T10:51:34Z" finished-at="2019-12-20T10:53:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.PlacementPageTest.verifySubmitForApprovalFunctionality1(PlacementPageTest.java:2203)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySubmitForApprovalFunctionality1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="getResult" is-config="true" duration-ms="1993" started-at="2019-12-20T10:53:07Z" finished-at="2019-12-20T10:53:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifySubmitForApprovalFunctionality1 status=FAILURE method=PlacementPageTest.verifySubmitForApprovalFunctionality1()[pri:35, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setUp" is-config="true" duration-ms="5988" started-at="2019-12-20T10:53:09Z" finished-at="2019-12-20T10:53:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyRejectPlacementFunctionality_Validations()[pri:37, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="verifyRejectPlacementFunctionality_Validations" duration-ms="75165" started-at="2019-12-20T10:53:15Z" finished-at="2019-12-20T10:54:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.PlacementPageTest.verifyRejectPlacementFunctionality_Validations(PlacementPageTest.java:2523)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRejectPlacementFunctionality_Validations -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="getResult" is-config="true" duration-ms="2035" started-at="2019-12-20T10:54:30Z" finished-at="2019-12-20T10:54:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyRejectPlacementFunctionality_Validations status=FAILURE method=PlacementPageTest.verifyRejectPlacementFunctionality_Validations()[pri:37, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setupAfterSuite()[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="setupAfterSuite" is-config="true" duration-ms="125" started-at="2019-12-20T10:54:32Z" finished-at="2019-12-20T10:54:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupAfterSuite -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.staff.qa.testcases.PlacementPageTest@59ec2012]" name="endReport" is-config="true" duration-ms="255" started-at="2019-12-20T10:54:32Z" finished-at="2019-12-20T10:54:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.staff.qa.testcases.PlacementPageTest -->
    </test> <!-- Test(failed)(failed)(failed) -->
  </suite> <!-- Failed suite [Failed suite [Failed suite [Suite]]] -->
</testng-results>
