<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Vijay-CH" ignored="0" name="Test" tests="9" failures="1" timestamp="07 Nov 2019 14:18:24 GMT" time="76.184" errors="0">
  <testcase name="loginPageTitleTest" time="0.018" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="loginTest" time="2.336" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validateLoginFunctionalityForIncorrectUserNamePassword" time="2.312" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validateMessageForBlankPasswordIncorrectUsername" time="2.315" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validateMessageForBlankUsernamePassword" time="2.287" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validatePasswordMessageForBlankPassword" time="2.316" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validatePasswordMessageForIncorrectPassword" time="2.358" classname="com.staff.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.staff.qa.testcases.LoginPageTest.validatePasswordMessageForIncorrectPassword(LoginPageTest.java:210)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- validatePasswordMessageForIncorrectPassword -->
  <testcase name="validateUsernameMessageForBalankUsername" time="2.268" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validateUsernameMessageForIncorrectUsername" time="2.396" classname="com.staff.qa.testcases.LoginPageTest"/>
</testsuite> <!-- Test -->
