<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vijay-CH" name="com.staff.qa.testcases.ConsultantPageTest" tests="23" failures="4" timestamp="04 Oct 2019 04:49:29 GMT" time="625.443" errors="0">
  <testcase name="verifyUserNavigateToConsultantPage" time="8.441" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyAddNewConsulatantFormDisplayed" time="13.932" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyAddNewConsultant" time="74.382" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyDuplicateConsultant" time="65.157" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyFunctionalityOfCancelButton" time="15.875" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="getAvailableCount" time="11.966" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="getAllCount" time="17.921" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="getArchivedCount" time="19.702" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="getQualifiedCount" time="17.929" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyEditConsultantFunctionality" time="78.385" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyUploadDocumentFunctionality" time="31.223" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyUploadDocumentAppearInGrid" time="30.652" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyDownloadUploadedDocument" time="22.289" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyLinkRequirementToConsultant" time="24.919" classname="com.staff.qa.testcases.ConsultantPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.ConsultantPageTest.verifyLinkRequirementToConsultant(ConsultantPageTest.java:686)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLinkRequirementToConsultant -->
  <testcase name="verifyLinkRequirementToConsultant_alreadyExists" time="33.287" classname="com.staff.qa.testcases.ConsultantPageTest">
    <failure type="java.lang.AssertionError" message="expected [Duplicate status can not be set as Shortlisted status already exists.] but found [Requirements are linked successfully.]">
      <![CDATA[java.lang.AssertionError: expected [Duplicate status can not be set as Shortlisted status already exists.] but found [Requirements are linked successfully.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.staff.qa.testcases.ConsultantPageTest.verifyLinkRequirementToConsultant_alreadyExists(ConsultantPageTest.java:722)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLinkRequirementToConsultant_alreadyExists -->
  <testcase name="verifyDownloadResumeFunctionality" time="23.089" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyCancelFunctionalityOfLinkRequirement" time="26.925" classname="com.staff.qa.testcases.ConsultantPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.ConsultantPageTest.verifyCancelFunctionalityOfLinkRequirement(ConsultantPageTest.java:815)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCancelFunctionalityOfLinkRequirement -->
  <testcase name="verifyEmailFunctionality" time="22.765" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyCancelButtonFunctionalityOfEmail" time="26.793" classname="com.staff.qa.testcases.ConsultantPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.ConsultantPageTest.verifyCancelButtonFunctionalityOfEmail(ConsultantPageTest.java:898)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCancelButtonFunctionalityOfEmail -->
  <testcase name="verifyValidationForEmailSubject" time="20.240" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyArchiveFunctionality" time="14.838" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyUn_ArchiveFunctionality" time="13.852" classname="com.staff.qa.testcases.ConsultantPageTest"/>
  <testcase name="verifyPageLable" time="10.881" classname="com.staff.qa.testcases.ConsultantPageTest"/>
</testsuite> <!-- com.staff.qa.testcases.ConsultantPageTest -->
